In [125]:
import pandas as pd

In [126]:
df=pd.read_csv("Feature engineering _ dataset.csv")
df

,Employee_ID,Name,Age,Gender,City,Department,Education,Experience_Years,Salary,Performance_Score,Performance_Rating,Join_Date,Email,Phone,Loan_Approved
0,EMP1339,Ravi Saxena,56,Male,Mumbai,Data Science,Diploma,31,163755,83,Good,2017-08-31,ravi.saxena97@gmail.com,9.794577e+09,Yes
1,EMP1040,Sanjay Malhotra,40,Male,DELHI,Sales,Master's,16,97043,68,Good,2022-09-26,sanjay.malhotra66gmail.com,9.570596e+09,No
2,EMP1186,Kiran Trivedi,53,Male,Kolkata,Data Science,Master's,30,156862,75,Excellent,2019-01-09,kiran.trivedi43@gmail.com,9.522802e+09,Yes
3,EMP1476,Priya Shah,48 years,Female,Pune,HR,Bachelor's,23,133665 rupees,68,Average,invalid,priya.shah61@gmail.com,9.563370e+09,No
4,EMP1030,Suresh Rao,28,Female,Jaipur,Marketing,Bachelor's,3,35848,94%,Good,2021-03-28,suresh.rao57gmail.com,9.149369e+09,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,EMP1201,Divya Rao,22,Female,Surat,HR,High School,0,31616,92,Excellent,2018-11-09,divya.rao35@gmail.com,9.331538e+09,Yes
508,EMP1168,Rohit Patel,26,M,Mumbai,HR,PhD,2 yrs,29004,59,Good,2015-11-10,rohit.patel94@gmail.com,9.877348e+09,Yes
509,EMP1185,Vikram Iyer,48,Male,Delhi,Data Science,Diploma,24,137690,84,Good,2016-10-22,vikram.iyer46@gmail.com,9.375738e+09,Yes
510,EMP1035,Swati Joshi,47,Female,Surat,Sales,Master's,22,124763,92,Average,2022-11-18,swati.joshi97@gmail.com,9.816851e+09,No
511,EMP1129,Anjali Shah,28,Male,Ahmedabad,Support,Diploma,6 yrs,48108,52,Average,2022-12-28,anjali.shah12@gmail.com,9.038458e+09,No

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512 entries, 0 to 511
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         512 non-null    object
 1   Name                512 non-null    object
 2   Age                 468 non-null    object
 3   Gender              492 non-null    object
 4   City                501 non-null    object
 5   Department          506 non-null    object
 6   Education           492 non-null    object
 7   Experience_Years    497 non-null    object
 8   Salary              497 non-null    object
 9   Performance_Score   482 non-null    object
 10  Performance_Rating  494 non-null    object
 11  Join_Date           512 non-null    object
 12  Email               495 non-null    object
 13  Phone               491 non-null    float64
 14  Loan_Approved       493 non-null    object
dtypes: float64(1), object(14)
memory usage: 60.1+ KB

In [128]:
df.describe()

              Phone
count  4.910000e+02
mean   9.490994e+09
std    2.802478e+08
min    9.002447e+09
25%    9.263092e+09
50%    9.482074e+09
75%    9.734860e+09
max    9.997047e+09

# SECTION 1 — DATA EXPLORATION & INITIAL CLEANING


 # Q1. DATA OVERVIEW 


 Write code to:

   a) Print the shape of the dataset
  
   b) Display the first 10 rows

   c) Show dtypes of every column

   d) Print the count of missing values per column

   e) Print the percentage of missing values per column (round to 2 decimals)

In [129]:
df.shape

(512, 15)

In [130]:
df.head()

,Employee_ID,Name,Age,Gender,City,Department,Education,Experience_Years,Salary,Performance_Score,Performance_Rating,Join_Date,Email,Phone,Loan_Approved
0,EMP1339,Ravi Saxena,56,Male,Mumbai,Data Science,Diploma,31,163755,83,Good,2017-08-31,ravi.saxena97@gmail.com,9.794577e+09,Yes
1,EMP1040,Sanjay Malhotra,40,Male,DELHI,Sales,Master's,16,97043,68,Good,2022-09-26,sanjay.malhotra66gmail.com,9.570596e+09,No
2,EMP1186,Kiran Trivedi,53,Male,Kolkata,Data Science,Master's,30,156862,75,Excellent,2019-01-09,kiran.trivedi43@gmail.com,9.522802e+09,Yes
3,EMP1476,Priya Shah,48 years,Female,Pune,HR,Bachelor's,23,133665 rupees,68,Average,invalid,priya.shah61@gmail.com,9.563370e+09,No
4,EMP1030,Suresh Rao,28,Female,Jaipur,Marketing,Bachelor's,3,35848,94%,Good,2021-03-28,suresh.rao57gmail.com,9.149369e+09,Yes

In [131]:
df.dtypes

Employee_ID            object
Name                   object
Age                    object
Gender                 object
City                   object
Department             object
Education              object
Experience_Years       object
Salary                 object
Performance_Score      object
Performance_Rating     object
Join_Date              object
Email                  object
Phone                 float64
Loan_Approved          object
dtype: object

In [132]:
df.isnull().sum()

Employee_ID            0
Name                   0
Age                   44
Gender                20
City                  11
Department             6
Education             20
Experience_Years      15
Salary                15
Performance_Score     30
Performance_Rating    18
Join_Date              0
Email                 17
Phone                 21
Loan_Approved         19
dtype: int64

In [133]:
per=((df.isnull().sum()/len(df))*100).round(2)
per

Employee_ID           0.00
Name                  0.00
Age                   8.59
Gender                3.91
City                  2.15
Department            1.17
Education             3.91
Experience_Years      2.93
Salary                2.93
Performance_Score     5.86
Performance_Rating    3.52
Join_Date             0.00
Email                 3.32
Phone                 4.10
Loan_Approved         3.71
dtype: float64

# Q2. DUPLICATE DETECTION & REMOVAL [4 marks]


The dataset contains intentionally duplicated rows.

   a) Count how many duplicate rows exist

   b) Show the duplicate rows

   c) Remove duplicates, keeping the first occurrence

   d) Confirm shape after removal

In [134]:
df.duplicated().sum()

np.int64(12)

In [135]:
df[df.duplicated]

,Employee_ID,Name,Age,Gender,City,Department,Education,Experience_Years,Salary,Performance_Score,Performance_Rating,Join_Date,Email,Phone,Loan_Approved
159,EMP1234,Manish Gupta,43,Male,Pune,Support,Diploma,19,108307,NaN,Excellent,2021-07-21,manish.gupta59@gmail.com,9.112911e+09,No
194,EMP1357,Meera Nair,50,Female,Mumbai,Engineering,Diploma,25,145815,100,Average,2017-08-06,meera.nair16@gmail.com,9.451958e+09,Yes
242,EMP1230,Suresh Chopra,40,Male,HYDERABAD,Engineering,Diploma,15,89625,99,NaN,2020-10-12,suresh.chopra14@gmail.com,9.797051e+09,No
248,EMP1421,Kiran Gupta,53,Male,Pune,Legal,Master's,29,163238,8000.0,Good,2021-08-06,kiran.gupta64@gmail.com,9.559428e+09,No
267,EMP1273,Ravi Mehta,44,Female,Hyderabad,Finance,Bachelor's,19,116186 rupees,82,Good,2015-11-11,ravi.mehta19@gmail.com,9.483754e+09,No
340,EMP1203,Ranjit Mishra,26,male,Bangalore,HR,Bachelor's,3,45950,64,Good,2021-09-21,ranjit.mishra64@gmail.com,9.309938e+09,Yes
342,EMP1223,Shreya Joshi,31,Female,HYDERABAD,Marketing,High School,7,65363,46,Average,2019-10-16,shreya.joshi96@gmail.com,9.201572e+09,Yes
348,EMP1030,Suresh Rao,28,Female,Jaipur,Marketing,Bachelor's,3,35848,94%,Good,2021-03-28,suresh.rao57gmail.com,9.149369e+09,Yes
395,EMP1387,Nisha Patel,39,Male,Jaipur,Legal,High School,15,100599,82,Excellent,2019-07-12,nisha.patel15@gmail.com,9.461540e+09,NaN
412,EMP1031,Rajesh Joshi,42,Female,Surat,Support,High School,20,110098,NaN,Excellent,2015-12-01,NaN,9.767976e+09,No
428,EMP1083,Seema Pandey,33,Male,Kolkata,Operations,Bachelor's,NaN,52462,56,Average,2017-12-14,seema.pandey38@gmail.com,9.490212e+09,Yes
494,EMP1221,Lakshmi Pandey,58,Male,Mumbai,Finance,High School,35 yrs,185218,67,Good,2019-02-04,lakshmi.pandey96@gmail.com,9.289932e+09,Yes

In [136]:
df.drop_duplicates(keep='first',inplace=True)

In [137]:
df.shape

(500, 15)

In [138]:
df_raw = df.copy()
df_raw

,Employee_ID,Name,Age,Gender,City,Department,Education,Experience_Years,Salary,Performance_Score,Performance_Rating,Join_Date,Email,Phone,Loan_Approved
0,EMP1339,Ravi Saxena,56,Male,Mumbai,Data Science,Diploma,31,163755,83,Good,2017-08-31,ravi.saxena97@gmail.com,9.794577e+09,Yes
1,EMP1040,Sanjay Malhotra,40,Male,DELHI,Sales,Master's,16,97043,68,Good,2022-09-26,sanjay.malhotra66gmail.com,9.570596e+09,No
2,EMP1186,Kiran Trivedi,53,Male,Kolkata,Data Science,Master's,30,156862,75,Excellent,2019-01-09,kiran.trivedi43@gmail.com,9.522802e+09,Yes
3,EMP1476,Priya Shah,48 years,Female,Pune,HR,Bachelor's,23,133665 rupees,68,Average,invalid,priya.shah61@gmail.com,9.563370e+09,No
4,EMP1030,Suresh Rao,28,Female,Jaipur,Marketing,Bachelor's,3,35848,94%,Good,2021-03-28,suresh.rao57gmail.com,9.149369e+09,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,EMP1201,Divya Rao,22,Female,Surat,HR,High School,0,31616,92,Excellent,2018-11-09,divya.rao35@gmail.com,9.331538e+09,Yes
508,EMP1168,Rohit Patel,26,M,Mumbai,HR,PhD,2 yrs,29004,59,Good,2015-11-10,rohit.patel94@gmail.com,9.877348e+09,Yes
509,EMP1185,Vikram Iyer,48,Male,Delhi,Data Science,Diploma,24,137690,84,Good,2016-10-22,vikram.iyer46@gmail.com,9.375738e+09,Yes
510,EMP1035,Swati Joshi,47,Female,Surat,Sales,Master's,22,124763,92,Average,2022-11-18,swati.joshi97@gmail.com,9.816851e+09,No
511,EMP1129,Anjali Shah,28,Male,Ahmedabad,Support,Diploma,6 yrs,48108,52,Average,2022-12-28,anjali.shah12@gmail.com,9.038458e+09,No

───────
# Q3. FIXING THE GENDER COLUMN


 The Gender column contains inconsistent values:

   "Male", "male", "MALE", "M", "1"  →  should all become  "Male"

   "Female", "female", "FEMALE", "F", "0"  →  should all become  "Female"

   a) Print all unique values in Gender column before cleaning

   b) Write a function clean_gender(val) that standardises the value

   c) Apply it to create a new column  Gender_Clean

   d) Verify: print unique values of Gender_Clean

In [139]:
df['Gender'].unique()

array(['Male', 'Female', 'F', 'M', 'female', '0', 'FEMALE', 'male', nan,
       '1', 'MALE'], dtype=object)

In [140]:
import numpy as np
def clean_gender(val):
    if pd.isna(val):
        return np.nan
    val=str(val).strip().lower()

    if val in ['male','m','1']:
        return 'Male'
    elif val in ['female','f','0']:
        return 'Female'
    else:
        return np.nan

In [141]:
df['Gender_clean']=df['Gender'].apply(clean_gender)

In [142]:
df['Gender_clean'].unique()

array(['Male', 'Female', nan], dtype=object)

# Q4. FIXING MIXED-FORMAT COLUMNS

 a) SALARY column contains values like "45000 rupees", "45k", "not disclosed",
 
    empty strings.  Convert everything to a numeric float (NaN where impossible).
    
    Store result in  Salary_Clean.

In [143]:
def clean_salary(val):
    if pd.isna(val):
        return np.nan
    val=str(val).strip().lower()
    if val in ['','not disclosed']:
        return np.nan
    val=val.replace('rupees','').replace('k','000').strip()
    try:
        return float(val)
    except:
        return np.nan

In [144]:
df['Salary_Clean']=df['Salary'].apply(clean_salary)
df['Salary_Clean']

0      163755.0
1       97043.0
2      156862.0
3      133665.0
4       35848.0
         ...
507     31616.0
508     29004.0
509    137690.0
510    124763.0
511     48108.0
Name: Salary_Clean, Length: 500, dtype: float64

In [145]:
df.shape

(500, 17)

In [146]:
df['Salary_Clean'].unique()

array([ 163755.,   97043.,  156862.,  133665.,   35848.,   98959.,
        106388.,  166434.,  123270.,   85992.,   85783.,   38470.,
            nan,  144533.,  500000.,   25863.,  160960.,   86908.,
         99910.,   35018.,   19356.,   82148.,  170255.,   78942.,
        160030.,   15671.,  170182.,  167022.,   47121.,   70484.,
         91945.,   69684.,   89625.,  122451.,   86581.,   47169.,
         24042.,  187656.,  159518.,   17200.,   82386.,  172355.,
         70287.,  116186.,  186794.,  106982.,   25175.,   26000.,
        161726.,  130463.,  102440.,  150303.,   78347.,  141404.,
         23048.,  137404.,  110915.,  148368.,   43739.,   72096.,
        119346.,  169019.,   65037.,  172664.,  146818.,   36248.,
        151224.,  110901.,   82900.,   42696.,   49737.,   41341.,
        108307.,   82650.,   33408.,   42508.,  170592.,  117710.,
         98218.,   78801.,   65598.,   80136.,   78373.,   31384.,
         45633.,   83750.,  161771.,   66582.,  180873.,   34282.,
         47220.,   57612.,  172133.,  191435.,  170848.,   42968.,
        178155.,   33715.,  157313.,   33176.,   55197.,  152097.,
         82675.,  155655.,  133176.,   26128.,  132418.,   20311.,
         50739.,  146529.,   19684.,   37457.,   97396.,   63000.,
         92598.,  146340.,  168030.,   29204.,  164450.,  107201.,
        164367., 1200000.,   16768.,  174905.,   23410.,   56587.,
        138527.,  182661.,   62036.,  131617.,   26904.,  169030.,
        165077.,  145815.,   52536.,   20912.,  112725.,   30101.,
        136757.,   57154.,   46525.,  133724.,   97168.,  182419.,
         37981.,  136051.,   22958.,  128313.,   76008.,  136836.,
        135325.,  140627.,   58114.,   57320.,  100040.,  156039.,
        154047.,  146751.,  132186.,   51224.,   27498.,  135663.,
         46170.,   66028.,   60695.,   38876.,  151214.,  189524.,
         80462.,   45950.,  180383.,  120105.,   65363.,  144339.,
        105608.,   47816.,   55155.,   74339.,   43843.,  176395.,
        143179.,   72384.,  174578.,   66000.,   63606.,   32396.,
        153011.,   47000.,   52733.,  136120.,   66274.,   78839.,
         35068.,  154389.,   30390.,   53004.,   75446.,   27695.,
        189597.,   86145.,  145000.,   38119.,   16754.,   64896.,
         98401.,   65137.,  172994.,   50427.,   94852.,   22267.,
        115308.,  131415.,  163238.,  108588.,  100599.,  110320.,
        130625.,   33305.,  157841.,  134846.,  107559.,  131546.,
         86007.,  135446.,   65548.,   49882.,  161289.,  191557.,
        134096.,  171885.,  167342.,   33613.,   69040.,  129278.,
         36632.,  129947.,   62274.,   62044.,  177128.,   85069.,
         52462.,   76099.,  176852.,  105452.,   50000.,   80071.,
        103002.,  168951.,  105178.,   65782.,  179641.,   59257.,
        139984.,  136546.,   18785.,   39536.,   22816.,  110972.,
         32621.,   83950.,  170688.,   88644.,   97739.,  173245.,
         41018.,   35880.,  169701.,  168192.,  132042.,  750000.,
        131973.,  166696.,   74551.,   86000.,  125539.,   43587.,
         80804.,  149373.,   94367.,   97631.,  168897.,   15592.,
        137866.,  151416.,  179363.,   71681.,   46899.,   30889.,
         74355.,   68563.,   16385.,  123482.,  120171.,  128363.,
        123431.,  109162.,  177471.,  124178.,   98848.,   96745.,
        110098.,   85511.,   75454.,  171717.,   61512.,   73226.,
        118957.,  169174.,  115182.,   43307.,   77623.,  181000.,
         77881.,   76350.,  181224.,   52000.,  182844.,   34758.,
        178794.,   42374.,  139943.,   46857.,   36176.,   79844.,
         70391.,   74115.,   61868.,   77754.,   17958.,   57224.,
        145551.,  126645.,   93685.,   32098.,  137734.,  182236.,
         85071.,   19000.,   41510.,   74434.,  172443.,  115863.,
         64269.,   93338.,  150515.,  120773.,  161797.,   69477.,
        185218.,  172162.,  167308.,   67373.,  179928.,   39003.,
        107818.,   52865.,  160090.,  144654.,  143860.,   47473.,
        121663.,   44063.,   56820.,   89954.,  166454.,  177592.,
        119955.,   51682.,  114833.,   50179.,   79220.,   28601.,
        142003.,  189587.,   30462.,  138677.,   22049.,   33471.,
        136308.,  168377.,   43296.,   53025.,  111756.,   67428.,
         34016.,  110924.,  102520.,   26048.,   20607.,  163839.,
         21661.,   17384.,   93440.,  110849.,  146138.,  149557.,
         97030.,   49772.,  157053.,   82144.,   73236.,   20419.,
        104680.,   86023.,  129673.,   75330.,   34857.,   79720.,
         25666.,   63153.,   72389.,  115000.,   77590.,  124985.,
         53940.,  154333.,  119586.,   31359.,  115858.,   61726.,
         48594.,  130115.,  123521.,  118116.,   92879.,  108322.,
        100567.,  144328.,   43433.,  107217.,   39258.,  187213.,
         90678.,  161803.,   42515.,  147138.,  136488.,  114094.,
         53956.,  153981.,  153000.,  142836.,   28625.,   38276.,
        132329.,  128179.,  147816.,   55648.,  148492.,  129744.,
         67430.,   82980.,   76448.,   46658.,   70889.,  165065.,
         31616.,   29004.,  137690.,  124763.,   48108.])

<!-- b) AGE column has values like "35 years", 999, -5.
    Convert to numeric, replace impossible ages (< 18 or > 80) with NaN.
    Store result in  Age_Clean. -->

# b) AGE column has values like "35 years", 999, -5.
#    Convert to numeric, replace impossible ages (< 18 or > 80) with NaN.
#    Store result in  Age_Clean.

In [199]:
df['Age'].unique()

array(['56', '40', '53', '48 years', '28', '42', '41', '48', '37', '26',
       '46', '-5', '54', nan, '23', '24', '36', '32', '57', '34', '45',
       '35', '39', '30', '22', '58', '44', '25', '51', '55', '47', '52',
       '27', '999', '33', '29', '43', '38', '49', '50', '37 years', '31',
       '34 years', '50 years', '24 years', '29 years', '45 years'],
      dtype=object)

In [148]:
def clean_age(val):
    if pd.isna(val):
        return np.nan
    val=str(val).strip().lower()
    val=val.replace('years','')
    for a in val:
        if a<'18' or a>'80':
            return np.nan
    try:
        return int(val)
    except:
        return np.nan


df['Age_Clean']=df['Age'].apply(clean_age) 
df['Age_Clean']

0      56.0
1       NaN
2      53.0
3       NaN
4      28.0
       ...
507    22.0
508    26.0
509    48.0
510    47.0
511    28.0
Name: Age_Clean, Length: 500, dtype: float64

# c) PERFORMANCE_SCORE column has values like "78%", 150, -1.
#    Convert to numeric and cap valid range to 0–100 (replace outliers with NaN).
#    Store result in  Score_Clean.

In [149]:
def clean_score(val):
    if pd.isna(val):
        return np.nan
    
    val = str(val).replace('%', '').strip()
    
    try:
        score = float(val)
        if 0 <= score < 100:
            return score
        else:
            return np.nan
    except:
        return np.nan

df['Score_Clean'] = df['Performance_Score'].apply(clean_score)
df['Score_Clean']

0      83.0
1      68.0
2      75.0
3      68.0
4      94.0
       ...
507    92.0
508    59.0
509    84.0
510    92.0
511    52.0
Name: Score_Clean, Length: 500, dtype: float64

In [150]:
df['Score_Clean'].unique()

array([83., 68., 75., 94., 65., 81., 89., 43., 66., 78., 47., 72., 52.,
       95., nan, 55., 53., 76., 92., 77., 84., 50., 42., 44., 85., 99.,
       64., 79., 57., 98., 60., 40., 49., 96., 82., 41., 70., 58., 74.,
       73., 86., 97., 61., 63., 88., 45., 90., 69., 46., 67., 59., 80.,
       51., 54., 91., 93., 62., 56., 48., 71., 87.])

# d) EXPERIENCE_YEARS has values like "5 yrs", "fresher".
#    Convert "fresher" → 0, strip " yrs", convert to numeric.
#    Store result in  Experience_Clean.

In [151]:
def clean_experience(val):
    if pd.isna(val):
        return np.nan
    
    val = str(val).replace('fresher', '0').replace('yrs','').strip()
    
    try:
        return float(val)
    except:
        return np.nan

df['experience_Clean'] = df['Experience_Years'].apply(clean_experience)
df['experience_Clean']

0      31.0
1      16.0
2      30.0
3      23.0
4       3.0
       ...
507     0.0
508     2.0
509    24.0
510    22.0
511     6.0
Name: experience_Clean, Length: 500, dtype: float64

In [152]:
df['experience_Clean'].unique()

array([31., 16., 30., 23.,  3., 18., 17., 33., 15.,  4., 26.,  2., 14.,
        1.,  0., 12., 10., 32., nan, 22., 34.,  6., 36.,  9., 19., 35.,
       29., 24., 28.,  5., 11., 21.,  7., 13.,  8., 27., 20., 25.])

# SECTION 2 — HANDLING MISSING VALUES

# Q5. MEAN IMPUTATION
# ─────────────────────────────────────────────────────────────────────────────
 Fill missing values in  Age_Clean  with the column MEAN.
 
 Print: count of nulls before and after imputation.

In [153]:
df['Age_Clean'].isnull().sum()

np.int64(162)

In [154]:
df['Age_Clean']=df['Age_Clean'].fillna(df['Age_Clean'].mean())
df['Age_Clean']

0      56.000000
1      40.233728
2      53.000000
3      40.233728
4      28.000000
         ...
507    22.000000
508    26.000000
509    48.000000
510    47.000000
511    28.000000
Name: Age_Clean, Length: 500, dtype: float64

In [155]:
df['Age_Clean'].isnull().sum()

np.int64(0)

In [156]:
df['Age_Clean'].astype(int)

0      56
1      40
2      53
3      40
4      28
       ..
507    22
508    26
509    48
510    47
511    28
Name: Age_Clean, Length: 500, dtype: int64

 # Q6. MEDIAN IMPUTATION
 

 Salary_Clean has outliers (a few employees earn ₹5,00,000+).

 Because of outliers, MEDIAN is safer than mean.

 Fill missing Salary_Clean values with the MEDIAN.

 Also fill missing Experience_Clean with the MEDIAN.

In [157]:
df['Salary_Clean']=df['Salary_Clean'].fillna(df['Salary_Clean'].median())
df['Salary_Clean']

0      163755.0
1       97043.0
2      156862.0
3      133665.0
4       35848.0
         ...
507     31616.0
508     29004.0
509    137690.0
510    124763.0
511     48108.0
Name: Salary_Clean, Length: 500, dtype: float64

In [158]:
df['Salary_Clean'].astype(int)

0      163755
1       97043
2      156862
3      133665
4       35848
        ...
507     31616
508     29004
509    137690
510    124763
511     48108
Name: Salary_Clean, Length: 500, dtype: int64

In [159]:
df['experience_Clean']=df['experience_Clean'].fillna(df['experience_Clean'].median())
df['experience_Clean']

0      31.0
1      16.0
2      30.0
3      23.0
4       3.0
       ...
507     0.0
508     2.0
509    24.0
510    22.0
511     6.0
Name: experience_Clean, Length: 500, dtype: float64

In [160]:
df['experience_Clean'].astype(int)

0      31
1      16
2      30
3      23
4       3
       ..
507     0
508     2
509    24
510    22
511     6
Name: experience_Clean, Length: 500, dtype: int64

In [161]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department',
       'Education', 'Experience_Years', 'Salary', 'Performance_Score',
       'Performance_Rating', 'Join_Date', 'Email', 'Phone', 'Loan_Approved',
       'Gender_clean', 'Salary_Clean', 'Age_Clean', 'Score_Clean',
       'experience_Clean'],
      dtype='object')

# Q7. MODE IMPUTATION 
 

 Fill missing values for categorical columns using MODE:

   Gender_Clean, City, Department, Education, Performance_Rating

In [162]:
df['Gender_clean']=df['Gender_clean'].fillna(df['Gender_clean'].mode()[0])
df['Gender_clean']

0        Male
1        Male
2        Male
3      Female
4      Female
        ...
507    Female
508      Male
509      Male
510    Female
511      Male
Name: Gender_clean, Length: 500, dtype: object

In [163]:
df['City']=df['City'].fillna(df['City'].mode()[0])
df['City']

0         Mumbai
1          DELHI
2        Kolkata
3           Pune
4         Jaipur
         ...
507        Surat
508       Mumbai
509        Delhi
510        Surat
511    Ahmedabad
Name: City, Length: 500, dtype: object

In [164]:
df['Department']=df['Department'].fillna(df['Department'].mode()[0])
df['Department']

0      Data Science
1             Sales
2      Data Science
3                HR
4         Marketing
           ...
507              HR
508              HR
509    Data Science
510           Sales
511         Support
Name: Department, Length: 500, dtype: object

In [165]:
df['Education']=df['Education'].fillna(df['Education'].mode()[0])
df['Education']

0          Diploma
1         Master's
2         Master's
3       Bachelor's
4       Bachelor's
          ...
507    High School
508            PhD
509        Diploma
510       Master's
511        Diploma
Name: Education, Length: 500, dtype: object

In [166]:
df['Performance_Rating']=df['Performance_Rating'].fillna(df['Performance_Rating'].mode()[0])
df['Performance_Rating']

0           Good
1           Good
2      Excellent
3        Average
4           Good
         ...
507    Excellent
508         Good
509         Good
510      Average
511      Average
Name: Performance_Rating, Length: 500, dtype: object

In [167]:
df.isnull().sum()

Employee_ID            0
Name                   0
Age                   44
Gender                20
City                   0
Department             0
Education              0
Experience_Years      14
Salary                15
Performance_Score     28
Performance_Rating     0
Join_Date              0
Email                 16
Phone                 21
Loan_Approved         18
Gender_clean           0
Salary_Clean           0
Age_Clean              0
Score_Clean           70
experience_Clean       0
dtype: int64

# Q8. SCORE IMPUTATION WITH GROUPED MEAN
 

 Instead of filling Score_Clean with the global mean, fill it with the

 mean score grouped by Department.

 (Employees in Data Science may score differently than HR employees!)


 Hint: use groupby + transform('mean')

In [168]:
df['Score_Clean'] = df['Score_Clean'].fillna(
    df.groupby('Department')['Score_Clean'].transform('mean')
)
df['Score_Clean']

0      83.0
1      68.0
2      75.0
3      68.0
4      94.0
       ...
507    92.0
508    59.0
509    84.0
510    92.0
511    52.0
Name: Score_Clean, Length: 500, dtype: float64

In [169]:
df['Score_Clean'].isnull().sum()

np.int64(0)

# Q9. LOAN APPROVED — FORWARD FILL 
 

 a) Fill missing Loan_Approved values using FORWARD FILL (ffill)

 b) Then fill any remaining NaN using BACKWARD FILL (bfill) as a safety net

 c) Print null count after both steps

In [170]:
df['Loan_Approved'] = df['Loan_Approved'].ffill()
df['Loan_Approved'] = df['Loan_Approved'].bfill()
df['Loan_Approved']

0      Yes
1       No
2      Yes
3       No
4      Yes
      ...
507    Yes
508    Yes
509    Yes
510     No
511     No
Name: Loan_Approved, Length: 500, dtype: object

In [171]:
df['Loan_Approved'].isnull().sum()

np.int64(0)

In [172]:
df.isnull().sum()

Employee_ID            0
Name                   0
Age                   44
Gender                20
City                   0
Department             0
Education              0
Experience_Years      14
Salary                15
Performance_Score     28
Performance_Rating     0
Join_Date              0
Email                 16
Phone                 21
Loan_Approved          0
Gender_clean           0
Salary_Clean           0
Age_Clean              0
Score_Clean            0
experience_Clean       0
dtype: int64

# SECTION 3 — CATEGORICAL ENCODING

# Q10. LABEL ENCODING — Gender

In [173]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

le = LabelEncoder()
df['Gender_Encoded'] = le.fit_transform(df['Gender_clean'])
print("Mapping:", dict(zip(le.classes_, le.transform(le.classes_))))
print(df['Gender_Encoded'].value_counts())

Mapping: {'Female': np.int64(0), 'Male': np.int64(1)}
Gender_Encoded
1    290
0    210
Name: count, dtype: int64

# Q11. LABEL ENCODING — Loan_Approved

In [174]:
le = LabelEncoder()
df['Gender_Encoded'] = le.fit_transform(df['Gender_clean'])
print("Mapping:", dict(zip(le.classes_, le.transform(le.classes_))))
print(df['Gender_Encoded'].value_counts())

Mapping: {'Female': np.int64(0), 'Male': np.int64(1)}
Gender_Encoded
1    290
0    210
Name: count, dtype: int64

In [175]:
df['Loan_Encoded'] = df['Loan_Approved'].map({'Yes': 1, 'No': 0})
print(df['Loan_Encoded'].head(10))

0    1
1    0
2    1
3    0
4    1
5    0
6    0
7    1
8    0
9    0
Name: Loan_Encoded, dtype: int64

# Q12. ONE-HOT ENCODING — Department

Department has 10+ categories with NO natural order.

 a) Apply pd.get_dummies() to create one-hot columns, using prefix="Dept"

 b) Drop the ORIGINAL Department column from df

 c) Add the dummy columns to df
 
 d) Print the names of all new dummy columns
 
  e) Print the shape of df before and after

In [176]:
print("Shape before:", df.shape)

Shape before: (500, 22)

In [177]:
dept_dummies = pd.get_dummies(df['Department'], prefix='Dept')
print("New dummy columns:", dept_dummies.columns.tolist())
df = df.drop(columns=['Department'])
df = pd.concat([df, dept_dummies], axis=1)

New dummy columns: ['Dept_Data Science', 'Dept_Design', 'Dept_Engineering', 'Dept_Finance', 'Dept_HR', 'Dept_Legal', 'Dept_Marketing', 'Dept_Operations', 'Dept_Sales', 'Dept_Support']

In [178]:
print("Shape after:", df.shape)

Shape after: (500, 31)

# Q13. ONE-HOT ENCODING — City 
# ─────────────────────────────────────────────────────────────────────────────
a) First clean the City column: strip whitespace, title-case everything

    e.g. "mumbai ", "MUMBAI" → "Mumbai"
    
 b) Apply One-Hot Encoding with drop_first=True to avoid dummy variable trap
 
    Use prefix='City'
    
c) Merge dummies into df and drop original City column

 d) How many new columns were created? Print that number.

In [179]:
df['City'] = df['City'].str.strip().str.title()
city_dummies = pd.get_dummies(df['City'], prefix='City', drop_first=True)
print("New city columns created:", city_dummies.shape[1])
df = df.drop(columns=['City'])
df = pd.concat([df, city_dummies], axis=1)

New city columns created: 9

# Q14. ORDINAL ENCODING — Education 
Education has a clear ORDER:

    High School < Diploma < Bachelor's < Master's < PhD
    
 a) Define the ordered category list
 
 b) Use sklearn OrdinalEncoder with the categories defined in (a)
 
 c) Store result in  Education_Encoded  (integer 1–5)
 
 d) Print a cross-tab of Education vs Education_Encoded to verify correctness
 
 e) Why would Label Encoding be WRONG here?  (comment answer)

In [180]:
edu_order = [['High School', 'Diploma', "Bachelor's", "Master's", 'PhD']]
oe = OrdinalEncoder(categories=edu_order)
df['Education_Encoded'] = oe.fit_transform(df[['Education']]).astype(int) + 1
print(pd.crosstab(df['Education'], df['Education_Encoded']))

Education_Encoded   1   2   3   4    5
Education
Bachelor's          0   0  89   0    0
Diploma             0  99   0   0    0
High School        90   0   0   0    0
Master's            0   0   0  93    0
PhD                 0   0   0   0  129

# Q15. ORDINAL ENCODING — Performance_Rating 

Performance_Rating order:  Poor < Average < Good < Excellent


 a) Map this manually using a dictionary (without sklearn)

 b) Store result in  Rating_Encoded

 c) Print crosstab: Performance_Rating vs Rating_Encoded

In [181]:
rating_map = {'Poor': 1, 'Average': 2, 'Good': 3, 'Excellent': 4}
df['Rating_Encoded'] = df['Performance_Rating'].map(rating_map)
print(pd.crosstab(df['Performance_Rating'], df['Rating_Encoded']))

Rating_Encoded       1    2    3    4
Performance_Rating
Average              0  129    0    0
Excellent            0    0    0  120
Good                 0    0  200    0
Poor                51    0    0    0

# Q16. MEAN / TARGET ENCODING — City → Salary
# ─────────────────────────────────────────────────────────────────────────────

Instead of one-hot encoding City (which creates many columns), replace each

 city with the MEAN Salary of employees from that city.

 (Use City column before you dropped it — re-read from df_raw if needed)


 a) Compute mean Salary_Clean per city

 b) Map each city to its mean salary → new column  City_MeanSalary

 c) Print the mean salary per city sorted descending

 d) What is a key RISK of mean encoding on small datasets? (comment answer)

In [182]:
df2 = df_raw.copy()
df2['City'] = df2['City'].str.strip().str.title()
df2['Salary_Clean'] = df2['Salary'].apply(clean_salary)

city_mean_salary = df2.groupby('City')['Salary_Clean'].mean()
df2['City_MeanSalary'] = df2['City'].map(city_mean_salary)
print(city_mean_salary.sort_values(ascending=False))

City
Chennai      132360.857143
Hyderabad    130484.345455
Delhi        123643.000000
Bangalore    117639.255319
Pune         115512.160714
Mumbai       109803.681818
Surat        108216.410714
Ahmedabad    103506.878049
Jaipur        93544.860465
Kolkata       86372.625000
Name: Salary_Clean, dtype: float64

# SECTION 4 — OUTLIER DETECTION & TREATMENT

 

# Q17. OUTLIER DETECTION — IQR METHOD on Salary 
─────────────────────────────────────────────────────────────────────────────
 a) Calculate Q1, Q3, and IQR for Salary_Clean
 
 b) Define lower and upper bounds: Q1 − 1.5×IQR  and  Q3 + 1.5×IQR

 c) Print count of outliers below lower bound and above upper bound

 d) Print the actual outlier salary values

 e) TREAT outliers using CAPPING (Winsorization):

    replace values below lower with lower, above upper with upper
    Store result in  Salary_Capped

 f) Verify: print min and max of Salary_Capped

In [189]:
Q1 = df["Salary_Clean"].quantile(0.25)
Q3 = df["Salary_Clean"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Below:", (df["Salary_Clean"] < lower).sum())
print("Above:", (df["Salary_Clean"] > upper).sum())

df["Salary_Capped"] = df["Salary_Clean"].clip(lower, upper)

Below: 0
Above: 9

In [188]:
# e) Capping (Winsorization)
df['Salary_Capped'] = df['Salary_Clean'].clip(lower=lower, upper=upper)
print("Min:", df['Salary_Capped'].min(), "Max:", df['Salary_Capped'].max())

Min: 15592.0 Max: 265219.25

# Q18. OUTLIER DETECTION — Z-SCORE METHOD on Score_Clean 

 a) Calculate Z-score for every value in Score_Clean
#    Z = (x − mean) / std

 b) Flag rows where |Z| > 3 as outliers

 c) Print count of flagged outliers

 d) Remove (drop) outlier rows from df for Score_Clean

 e) Print shape before and after removal

In [184]:
mean = df["Score_Clean"].mean()
std = df["Score_Clean"].std()

df["Z"] = (df["Score_Clean"] - mean) / std

print("Outliers:", (df["Z"].abs() > 3).sum())

shape_before = df.shape
df = df[df["Z"].abs() <= 3]
print("Before:", shape_before)
print("After:", df.shape)

df.drop("Z", axis=1, inplace=True)

Outliers: 0
Before: (500, 43)
After: (500, 43)

═════════════
# SECTION 5 — NEW FEATURE CREATION


# Q19. FEATURE CREATION — Date-based Features 


 Join_Date column has mixed formats (YYYY-MM-DD, DD/MM/YYYY, "invalid", etc.)

 a) Parse Join_Date to datetime using pd.to_datetime with errors='coerce'

 b) Fill NaT values with the median date

 c) Create new column  Tenure_Years  = (today's date − join date) / 365
    Round to 1 decimal

 d) Create new column  Join_Year   (integer year)

 e) Create new column  Join_Quarter  (1, 2, 3, or 4)

In [187]:
df["Join_Date"] = pd.to_datetime(df["Join_Date"], errors="coerce")

median_date = df["Join_Date"].median()
df["Join_Date"].fillna(median_date, inplace=True)

today = pd.Timestamp.today()

df["Tenure_Years"] = ((today - df["Join_Date"]).dt.days / 365).round(1)
df["Join_Year"] = df["Join_Date"].dt.year
df["Join_Quarter"] = df["Join_Date"].dt.quarter

C:\Users\vinut\AppData\Local\Temp\ipykernel_18972\2078233633.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Join_Date"].fillna(median_date, inplace=True)

In [190]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Education', 'Experience_Years',
       'Salary', 'Performance_Score', 'Performance_Rating', 'Join_Date',
       'Email', 'Phone', 'Loan_Approved', 'Gender_clean', 'Salary_Clean',
       'Age_Clean', 'Score_Clean', 'experience_Clean', 'Gender_Encoded',
       'Loan_Encoded', 'Dept_Data Science', 'Dept_Design', 'Dept_Engineering',
       'Dept_Finance', 'Dept_HR', 'Dept_Legal', 'Dept_Marketing',
       'Dept_Operations', 'Dept_Sales', 'Dept_Support', 'City_Bangalore',
       'City_Chennai', 'City_Delhi', 'City_Hyderabad', 'City_Jaipur',
       'City_Kolkata', 'City_Mumbai', 'City_Pune', 'City_Surat',
       'Education_Encoded', 'Rating_Encoded', 'Salary_Capped', 'Tenure_Years',
       'Join_Year', 'Join_Quarter'],
      dtype='object')

# Q20. FEATURE CREATION — Derived Numeric Features 
# ─────────────────────────────────────────────────────────────────────────────
 a) Create  Salary_Per_Year_Exp  = Salary_Capped / (Experience_Clean + 1)
   
    (+1 avoids division by zero for freshers)
   
    Round to 2 decimals.

b) Create  Score_Salary_Ratio  = Score_Clean / Salary_Capped * 1000

    (performance per ₹1000 earned — useful for ML ranking tasks)

    Round to 4 decimals.

 c) Create  Is_Senior  = 1 if Age_Clean >= 40 else 0

    (binary flag for senior employees)

 d) Create  Exp_Age_Ratio  = Experience_Clean / Age_Clean

    (what fraction of their life has been working experience?)
    Round to 3 decimals.


 e) Print describe() for all 4 new features

In [192]:
df["Salary_Per_Year_Exp"] = (df["Salary_Capped"] /
                             (df["experience_Clean"] + 1)).round(2)

df["Score_Salary_Ratio"] = (
    df["Score_Clean"] / df["Salary_Capped"] * 1000
).round(4)

df["Is_Senior"] = np.where(df["Age_Clean"] >= 40, 1, 0)

df["Exp_Age_Ratio"] = (
    df["experience_Clean"] / df["Age_Clean"]
).round(3)

print(df[["Salary_Per_Year_Exp",
          "Score_Salary_Ratio",
          "Is_Senior",
          "Exp_Age_Ratio"]].describe())

       Salary_Per_Year_Exp  Score_Salary_Ratio   Is_Senior  Exp_Age_Ratio
count           500.000000          500.000000  500.000000     500.000000
mean           9617.573700            1.015941    0.660000       0.364750
std           16062.071971            0.836628    0.474183       0.212418
min            2261.000000            0.173400    0.000000       0.000000
25%            5231.907500            0.499275    0.000000       0.177750
50%            5774.620000            0.716850    1.000000       0.395000
75%            7560.425000            1.208650    1.000000       0.545000
max          265219.250000            5.579800    1.000000       0.895000

# SECTION 6 — BINNING / BUCKETING
# ══════════════════════════════════════════════════════════════════════════════
 
 
# Q21. EQUAL-WIDTH BINNING — Age Groups 


 a) Use pd.cut() to bin Age_Clean into 4 equal-width bins

    Label them: "Young" (18–30), "Mid-Career" (30–42), "Senior" (42–54), "Veteran" (54–80)
   Store in  Age_Group

 b) Print value counts of Age_Group

 c) Now encode Age_Group as an ORDINAL numeric:
    Young=1, Mid-Career=2, Senio

In [193]:
df["Age_Group"] = pd.cut(df["Age_Clean"],
                         bins=4,
                         labels=["Young","Mid-Career",
                                 "Senior","Veteran"])

print(df["Age_Group"].value_counts())

age_map = {
    "Young":1,
    "Mid-Career":2,
    "Senior":3,
    "Veteran":4
}

df["Age_Group_Encoded"] = df["Age_Group"].map(age_map)

Age_Group
Senior        234
Veteran        96
Young          91
Mid-Career     79
Name: count, dtype: int64

# Q22. EQUAL-FREQUENCY BINNING — Salary Quantiles 
# ─────────────────────────────────────────────────────────────────────────────
 Equal-width bins for salary are unfair because of skew.
 Use pd.qcut() to create 4 quantile-based salary brackets.


 a) Use pd.qcut() with q=4 and labels ["Low","Lower-Mid","Upper-Mid","High"]

    Store in  Salary_Bracket



 b) Print value counts — notice all buckets are roughly equal size!


 c) Cross-tabulate Salary_Bracket vs Loan_Approved

    What pattern do you notice? (comment your observation)

In [194]:
df["Salary_Bracket"] = pd.qcut(df["Salary_Capped"],
                               q=4,
                               labels=["Low","Lower-Mid",
                                       "Upper-Mid","High"])

print(df["Salary_Bracket"].value_counts())
print(pd.crosstab(df["Salary_Bracket"], df["Loan_Approved"]))

Salary_Bracket
Lower-Mid    142
Low          125
High         125
Upper-Mid    108
Name: count, dtype: int64
Loan_Approved   No  Yes
Salary_Bracket
Low             53   72
Lower-Mid       72   70
Upper-Mid       53   55
High            57   68

# Q23. CUSTOM BINNING — Performance Score → Grade 
# ─────────────────────────────────────────────────────────────────────────────
 Convert numeric Score_Clean into letter grades:
   0–49  → "F"
   50–59 → "D"
   60–69 → "C"
   70–79 → "B"
   80–89 → "A"
   90–100→ "S"  (Distinction)


 a) Use pd.cut() with custom bins and labels above

 b) Store in  Score_Grade

 c) Print value counts

 d) One-hot encode Score_Grade using pd.get_dummies (prefix='Grade')
    and concatenate to df

In [195]:
bins = [0,49,59,69,79,89,100]
labels = ["F","D","C","B","A","S"]

df["Score_Grade"] = pd.cut(df["Score_Clean"],
                           bins=bins,
                           labels=labels)

print(df["Score_Grade"].value_counts())

grade_dummies = pd.get_dummies(df["Score_Grade"], prefix="Grade")
df = pd.concat([df, grade_dummies], axis=1)

Score_Grade
B    119
C     93
A     78
D     75
F     69
S     66
Name: count, dtype: int64

# Q24. MINI PIPELINE — Build a model-ready feature set 
# ─────────────────────────────────────────────────────────────────────────────

Starting from  df_raw.copy(), build a complete cleaned dataset called

 df_final  with ONLY the following final feature columns:


   Numeric (already cleaned/imputed):

     Age_Clean, Salary_Capped, Score_Clean, Experience_Clean, Tenure_Years

#   Engineered numeric:
     Salary_Per_Year_Exp, Is_Senior, Exp_Age_Ratio, Age_Group_Encoded,
     Rating_Encoded, Education_Encoded

#   Encoded categoricals:
     Gender_Encoded (0/1)

#   One-hot:
     Dept_* columns  (from Department)

#   Target variable:
     Loan_Encoded  (0/1)


 a) Perform all cleaning steps in sequence

 b) Select only the above columns

 c) Assert there are ZERO null values in df_final

 d) Print final shape and first 5 rows

In [197]:
final_columns = [
    "Age_Clean","Salary_Capped","Score_Clean",
    "experience_Clean","Tenure_Years",
    "Salary_Per_Year_Exp","Is_Senior",
    "Exp_Age_Ratio","Age_Group_Encoded",
    "Rating_Encoded","Education_Encoded",
    "Gender_Encoded","Loan_Encoded"
]

dept_cols = [col for col in df.columns if col.startswith("Dept_")]

df_final = df[final_columns + dept_cols]

# Check nulls
assert df_final.isnull().sum().sum() == 0

print("Final Shape:", df_final.shape)
print(df_final.head())

Final Shape: (500, 23)
   Age_Clean  Salary_Capped  Score_Clean  experience_Clean  Tenure_Years  \
0  56.000000       163755.0         83.0              31.0           8.6
1  40.233728        97043.0         68.0              16.0           3.5
2  53.000000       156862.0         75.0              30.0           7.2
3  40.233728       133665.0         68.0              23.0           7.1
4  28.000000        35848.0         94.0               3.0           5.0

   Salary_Per_Year_Exp  Is_Senior  Exp_Age_Ratio Age_Group_Encoded  \
0              5117.34          1          0.554                 4
1              5708.41          1          0.398                 3
2              5060.06          1          0.566                 4
3              5569.38          1          0.572                 3
4              8962.00          0          0.107                 1

   Rating_Encoded  ...  Dept_Data Science  Dept_Design  Dept_Engineering  \
0               3  ...               True        False             False
1               3  ...              False        False             False
2               4  ...               True        False             False
3               2  ...              False        False             False
4               3  ...              False        False             False

   Dept_Finance  Dept_HR  Dept_Legal  Dept_Marketing  Dept_Operations  \
0         False    False       False           False            False
1         False    False       False           False            False
2         False    False       False           False            False
3         False     True       False           False            False
4         False    False       False            True            False

   Dept_Sales  Dept_Support
0       False         False
1        True         False
2       False         False
3       False         False
4       False         False

[5 rows x 23 columns]

# Q25. BONUS — FREQUENCY ENCODING on City 
 ─────────────────────────────────────────────────────────────────────────────

 Frequency encoding replaces each category with how many times it appears.

 This is useful when many unique categories exist.



 a) Starting from df_raw, clean the City column (strip + title-case)

 b) Compute frequency count of each city

 c) Create column  City_Freq  by mapping each city to its frequency count

 d) Normalise City_Freq to 0–1 using Min-Max scaling and store as  City_Freq_Norm

 e) What happens if two different cities have the same frequency?
    Is that a problem? (comment your answer)

In [198]:
df3 = df_raw.copy()

df3["City"] = df3["City"].str.strip().str.title()

freq = df3["City"].value_counts()

df3["City_Freq"] = df3["City"].map(freq)

# Min-Max normalization
df3["City_Freq_Norm"] = (
    (df3["City_Freq"] - df3["City_Freq"].min()) /
    (df3["City_Freq"].max() - df3["City_Freq"].min())
)

print(df3[["City","City_Freq","City_Freq_Norm"]].head())

      City  City_Freq  City_Freq_Norm
0   Mumbai       48.0        0.518519
1    Delhi       38.0        0.148148
2  Kolkata       34.0        0.000000
3     Pune       59.0        0.925926
4   Jaipur       45.0        0.407407

e) Problem with equal-frequency cities:
 If Mumbai (50 employees) and Pune (50 employees) have the same count, they get
 the same encoded value. The model CANNOT distinguish them — two completely
 different cities become identical features. This is a known weakness of
 frequency encoding. Solution: combine frequency encoding with another encoding
(e.g. target encoding) or use embeddings for high-cardinality categoricals.